[profile.default]
out = 'out'
ffi = true
build_info = true
extra_output = ['storageLayout']
force = true
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"